<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Staffinity.Personal.Domain\Staffinity.Personal.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Vacations\Dto\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
